function [AvailGeom, MaskGeom] = setAvailGeom

% function [AvailGeom, MaskGeom] = setAvailGeom
% returns a list of available geometries 'AvailGeom' and the list of function
% handles to functions that create appropriate maska 'MaskGeom'
% Use 'vizMask.m' to visualize a particular geometry

AvailGeom = struct('type',{'Duct2D','CircDuct2D','Sphere2D','Sphere3D','SegFile3DMA',...
                           'Throat2D','Biconic2D','ThroatBump', 'ThroatBump1','ThroatHole',...
                             'Throat2Dsmall','Hybrid1', 'Hybrid2','Hybrid3','SquarePore',...
                             'SquarePore1','SquarePore2','SquarePore3','SquarePore4',...
                             'SquarePore5','SquarePore6','SquarePore7','SquarePore8',...
                             'SquarePore9','SquarePore10','SquarePore11','SquarePore12',...
                              'Sphere2Dall','Sphere2Dbig','Sphere2D_duct_ext','Sphere2D_orth_ext',...
                              'SpherePore1','SpherePore2', 'SpherePore3','SpherePore4','TetraPore1','RhomboidSpheres3D'});
MaskGeom  = struct('func',{@maskDuct2D,@maskCircDuct2D,@maskSphere2D,@maskSphere3D,@maskSegFile3DMA,...
                              @maskThroat2D, @maskBiconic2D,@maskThroatBump,@maskThroatBump1,...
                              @maskThroatHole,@maskThroat2Dsmall,@maskHybrid1,...
                              @maskHybrid2,@maskHybrid3,@maskSquarePore,@maskSquarePore1,@maskSquarePore2,...
                              @maskSquarePore3,@maskSquarePore4,@maskSquarePore5,@maskSquarePore6,...
                              @maskSquarePore7,@maskSquarePore8, @maskSquarePore9,...
                              @maskSquarePore10,@maskSquarePore11,@maskSquarePore12,...
                              @maskSphere2D, @maskSphere2D, @maskSphere2D_duct_ext,  @maskSphere2D_orth_ext,...
                              @maskSpherePore1,@maskSpherePore2, @maskSpherePore3,@maskSpherePore4,@maskTetraPore1,@rhomboidSpheres3D});
